---
galaxy_info:
  role_name: ocp4_workload_field_content
  author: Red Hat Demo Platform
  description: |
    Deploy field-sourced content via ArgoCD. Reference copy for documentation.
  license: MIT
  min_ansible_version: "2.9"
  platforms: []
  galaxy_tags:
  - ocp
  - openshift
  - argocd
  - gitops
dependencies: []
