{{- if .Values.demo.enabled }}
---
# Sample httpd application deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.demo.appName }}
  namespace: {{ .Values.demo.namespace }}
  labels:
    demo.redhat.com/application: "hello-world"
    app: {{ .Values.demo.appName }}
spec:
  replicas: {{ .Values.demo.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.demo.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.demo.appName }}
    spec:
      containers:
        - name: httpd
          image: {{ .Values.demo.image }}
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
{{- end }}
