{{- if .Values.demo.enabled }}
---
# Demo application namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.demo.namespace }}
  labels:
    demo.redhat.com/application: "hello-world"
{{- end }}
