{{- if .Values.demo.enabled }}
---
# Service for the demo application
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.demo.appName }}
  namespace: {{ .Values.demo.namespace }}
  labels:
    demo.redhat.com/application: "hello-world"
    app: {{ .Values.demo.appName }}
spec:
  selector:
    app: {{ .Values.demo.appName }}
  ports:
    - port: 8080
      targetPort: 8080
{{- end }}
