apiVersion: v2
name: field-content-demo
description: App of Apps - Deploy multiple components via ArgoCD Applications
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
  - name: Field Content Developer
    email: developer@redhat.com
