{{- if .Values.showroom.enabled }}
---
# Showroom Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.showroom.namespace | default "showroom" }}
  labels:
    demo.redhat.com/application: "showroom"
---
# Showroom ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.showroom.name }}
  namespace: {{ .Values.showroom.namespace }}
---
# Showroom RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-{{ .Values.showroom.name }}-sa
  namespace: {{ .Values.showroom.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ .Values.showroom.name }}
  namespace: {{ .Values.showroom.namespace }}
---
# Showroom Nginx ConfigMap
kind: ConfigMap
metadata:
  name: {{ .Values.showroom.name }}-proxy-config
  namespace: {{ .Values.showroom.namespace }}
apiVersion: v1
data:
  nginx.conf: |
    events {
    }
    error_log /dev/stdout info;
    http {
      include /etc/nginx/mime.types;
      proxy_cache off;
      expires -1;
      proxy_cache_path /dev/null keys_zone=mycache:10m;
      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }
      server {
        listen 8080;
        absolute_redirect off;
        location / {
          proxy_pass http://127.0.0.1:8000;
          expires off;
          proxy_cache off;
          proxy_pass_request_headers on;
          proxy_set_header Accept-Encoding "gzip";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        {{- if .Values.showroom.terminal.enabled }}
        location /terminal/ {
          proxy_pass http://127.0.0.1:7681;
          rewrite ^/terminal/(.*)$ /$1 break;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
        {{- end }}
      }
    }
---
# Showroom User Data ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.showroom.name }}-userdata
  namespace: {{ .Values.showroom.namespace }}
data:
  user_data.yml: |
    cluster_domain: {{ .Values.deployer.domain }}
    demo_namespace: {{ .Values.demo.namespace }}
    demo_app: {{ .Values.demo.appName }}
---
# Showroom PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.showroom.name }}-terminal-lab-user-home
  namespace: {{ .Values.showroom.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
---
# Showroom Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.showroom.name }}
  namespace: {{ .Values.showroom.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ .Values.showroom.name }}
---
# Showroom Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.showroom.name }}
  namespace: {{ .Values.showroom.namespace }}
  labels:
    demo.redhat.com/application: "showroom"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.showroom.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.showroom.name }}
    spec:
      serviceAccountName: {{ .Values.showroom.name }}
      initContainers:
      - name: git-cloner
        image: "quay.io/rhpds/git-cloner:v1.1.2"
        env:
        - name: GIT_REPO_URL
          value: {{ .Values.showroom.content.repoUrl | quote }}
        - name: GIT_REPO_REF
          value: {{ .Values.showroom.content.repoRef | quote }}
        - name: CLONE_DIR
          value: "/showroom/repo"
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
      - name: antora-builder
        image: "quay.io/rhpds/antora:v1.0.1"
        env:
        - name: FILES_DIR
          value: "/showroom/repo"
        - name: OUTPUT_DIR
          value: "/showroom/www"
        - name: ANTORA_SITE_FILE
          value: {{ .Values.showroom.content.antoraPlaybook | quote }}
        volumeMounts:
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/www
          name: showroom-files
          subPath: www
      containers:
      - name: nginx
        image: "quay.io/rhpds/nginx:1.25"
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-config
          subPath: nginx.conf
        - mountPath: /var/cache/nginx
          name: nginx-cache
        - mountPath: /var/run
          name: nginx-pid
        ports:
        - name: web
          containerPort: 8080
      - name: content
        image: {{ .Values.showroom.content.image | quote }}
        imagePullPolicy: "IfNotPresent"
        env:
        - name: GIT_REPO_URL
          value: {{ .Values.showroom.content.repoUrl | quote }}
        - name: GIT_REPO_REF
          value: {{ .Values.showroom.content.repoRef | quote }}
        - name: ANTORA_PLAYBOOK
          value: {{ .Values.showroom.content.antoraPlaybook | quote }}
        - name: DOMAIN
          value: {{ .Values.deployer.domain | quote }}
        {{- if .Values.showroom.nookbag.enabled }}
        - name: ZT_BUNDLE
          value: {{ .Values.showroom.nookbag.bundleUrl | quote }}
        - name: ZT_UI_ENABLED
          value: "true"
        - name: GUID
          value: {{ .Values.showroom.namespace | quote }}
        {{- end }}
        volumeMounts:
        - name: user-data
          mountPath: /user_data/
        - mountPath: /showroom/repo
          name: showroom-files
          subPath: repo
        - mountPath: /showroom/www
          name: showroom-files
          subPath: www
        ports:
        - containerPort: 8000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
      {{- if .Values.showroom.terminal.enabled }}
      - name: terminal
        image: {{ .Values.showroom.terminal.image | quote }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: terminal-lab-user-home
          mountPath: /home/lab-user
        ports:
        - containerPort: 7681
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.showroom.terminal.resources.limits.cpu }}
            memory: {{ .Values.showroom.terminal.resources.limits.memory }}
          requests:
            cpu: {{ .Values.showroom.terminal.resources.requests.cpu }}
            memory: {{ .Values.showroom.terminal.resources.requests.memory }}
      {{- end }}
      volumes:
      - name: showroom-files
        emptyDir: {}
      - name: user-data
        configMap:
          name: {{ .Values.showroom.name }}-userdata
      - name: nginx-config
        configMap:
          defaultMode: 420
          name: {{ .Values.showroom.name }}-proxy-config
      - name: nginx-pid
        emptyDir: {}
      - name: nginx-cache
        emptyDir: {}
      - name: terminal-lab-user-home
        persistentVolumeClaim:
          claimName: {{ .Values.showroom.name }}-terminal-lab-user-home
---
# Showroom Route
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.showroom.name }}
  namespace: {{ .Values.showroom.namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 1h
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  to:
    kind: Service
    name: {{ .Values.showroom.name }}
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
