{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ include "ansible-runner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    demo.redhat.com/application: "ansible-runner"
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWave.rbac | quote }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}